name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: registry.cn-hangzhou.aliyuncs.com/seayuns/cpp-complier:0.1
    steps: 
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
